config/routes.rb
Rails.application.routes.draw do
  resources :voluntarios
  resources :registros
  resources :registers
  get 'bienvenida/index'

end

app/models/country.rb
class Country < ActiveRecord::Base
end

app/models/register.rb
class Register < ActiveRecord::Base
end

app/models/registro.rb
class Registro < ActiveRecord::Base
end

app/models/voluntario.rb
class Voluntario < ActiveRecord::Base
mount_uploader :attachment, AttachmentUploader
validates :nombre, :presence => {:message => "Debes ingresar un Nombre"}, length: {minimum: 3, maximum: 20, :message => "El Nombre debe tener entre 3 a 20 caracteres"}
validates :apellido, :presence => {:message => "Debes ingresar un Apellido"}, length: {minimum: 3, maximum: 20, :message => "El Apellido debe tener entre 3 a 20 caracteres"}
validates :estado, :presence => {:message => "Debes ingresar un Estado"}
validates :municipio, :presence => {:message => "Debes ingresar un Municipio"}
validates :localidad, :presence => {:message => "Debes ingresar una Localidad"}, length: { minimum: 3, maximum: 15, :message => "La Localidad debe tener entre 3 a 15 caracteres"}
validates :colonia, :presence => {:message => "Debes ingresar una Colonia"}, length: { minimum: 3, maximum: 10, :message => "La Colonia debe tener entre 3 a 10 caracteres"}
validates :correo_electronico, :presence => {:message => "Debes ingresar un Email"}, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create, :message => "Form ato Email invalido" }
validates :telefono, :presence => {:message => "Debes ingresar una Teléfono"}, length: { minimum: 9, maximum: 11, :message => "El Teléfono debe tener entre 3 a 10 caracteres" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bienvenida_controller.rb
class BienvenidaController < ApplicationController
  def index
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_register, only: [:show, :edit, :update, :destroy]

  # GET /registers
  # GET /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1
  # GET /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = Register.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers
  # POST /registers.json
  def create
    @register = Register.new(register_params)

    respond_to do |format|
      if @register.save
        format.html { redirect_to @register, notice: 'Register was successfully created.' }
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: 'Register was successfully updated.' }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: 'Register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:register).permit(:numero, :nombregrupo, :estado, :municipio, :localidad, :colonia, :status)
    end
end

app/controllers/registros_controller.rb
class RegistrosController < ApplicationController
  before_action :set_registro, only: [:show, :edit, :update, :destroy]
def index
    @search = Registro.search(params[:q])
    @registros = @search.result
  end 
  # GET /registros
  # GET /registros.json
  def index
    @registros = Registro.all
  end

  # GET /registros/1
  # GET /registros/1.json
  def show
  end

  # GET /registros/new
  def new
    @registro = Registro.new
  end

  # GET /registros/1/edit
  def edit
  end

  # POST /registros
  # POST /registros.json
  def create
    @registro = Registro.new(registro_params)

    respond_to do |format|
      if @registro.save
        format.html { redirect_to @registro, notice: 'Registro was successfully created.' }
        format.json { render :show, status: :created, location: @registro }
      else
        format.html { render :new }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registros/1
  # PATCH/PUT /registros/1.json
  def update
    respond_to do |format|
      if @registro.update(registro_params)
        format.html { redirect_to @registro, notice: 'Registro was successfully updated.' }
        format.json { render :show, status: :ok, location: @registro }
      else
        format.html { render :edit }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registros/1
  # DELETE /registros/1.json
  def destroy
    @registro.destroy
    respond_to do |format|
      format.html { redirect_to registros_url, notice: 'Registro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registro
      @registro = Registro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registro_params
      params.require(:registro).permit(:numero, :nombregrupo, :estado, :municipio, :localidad, :colonia, :disponible)
    end
end

app/controllers/voluntarios_controller.rb
class VoluntariosController < ApplicationController
  before_action :set_voluntario, only: [:show, :edit, :update, :destroy]

  # GET /voluntarios
  # GET /voluntarios.json
  def index
    @search = Voluntario.search(params[:q])
    @voluntarios = @search.result.paginate(:page => params[:page], per_page: 10)
  
  end


  # GET /voluntarios/1
  # GET /voluntarios/1.json
  def show
  end

  # GET /voluntarios/new
  def new
    @voluntario = Voluntario.new
  end

  # GET /voluntarios/1/edit
  def edit
  end

  # POST /voluntarios
  # POST /voluntarios.json
  def create
    @voluntario = Voluntario.new(voluntario_params)

    respond_to do |format|
      if @voluntario.save
        format.html { redirect_to @voluntario, notice: 'Voluntario was successfully created.' }
        format.json { render :show, status: :created, location: @voluntario }
      else
        format.html { render :new }
        format.json { render json: @voluntario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voluntarios/1
  # PATCH/PUT /voluntarios/1.json
  def update
    respond_to do |format|
      if @voluntario.update(voluntario_params)
        format.html { redirect_to @voluntario, notice: 'Voluntario was successfully updated.' }
        format.json { render :show, status: :ok, location: @voluntario }
      else
        format.html { render :edit }
        format.json { render json: @voluntario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voluntarios/1
  # DELETE /voluntarios/1.json
  def destroy
    @voluntario.destroy
    respond_to do |format|
      format.html { redirect_to voluntarios_url, notice: 'Voluntario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voluntario
      @voluntario = Voluntario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voluntario_params
      params.require(:voluntario).permit(:contacto, :fecha_solicitud, :fecha_autorizacion, :numero_registro, :nombre, :apellido, :estado, :municipio, :localidad, :colonia, :correo_electronico, :telefono, :sub_grupos, :obra_publica, :status, :attachment, :comentarios)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenida_helper.rb
module BienvenidaHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/registros_helper.rb
module RegistrosHelper
end

app/helpers/voluntarios_helper.rb
module VoluntariosHelper
end

app/views/bienvenida/index.html.erb
<h1>Congregación Mariana Trinitaria</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appcmt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<%= javascript_include_tag 'http://code.jquery.com/jquery-latest.min.js' %>

</head>


<body>  
<nav class="navbar navbar-default ">
  <div class="container-fluid ">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header ">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navb-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Appcmt</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navb-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Dashboard <span class="sr-only">(current)</span></a></li>
                <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Solicitudes<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Agregar nueva', new_voluntario_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Buscar', voluntarios_path %></li>
     
             </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- Navigation -->
   
   
<%= yield %>

</body>
</html>

app/views/registers/_form.html.erb
<%= form_for(@register) do |f| %>
  <% if @register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% @register.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :nombregrupo %><br>
    <%= f.text_field :nombregrupo %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_field :estado %>
  </div>
  <div class="field">
    <%= f.label :municipio %><br>
    <%= f.text_field :municipio %>
  </div>
  <div class="field">
    <%= f.label :localidad %><br>
    <%= f.text_field :localidad %>
  </div>
  <div class="field">
    <%= f.label :colonia %><br>
    <%= f.text_field :colonia %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registers/edit.html.erb
<h1>Editing Register</h1>

<%= render 'form' %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Registers</h1>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Nombregrupo</th>
      <th>Estado</th>
      <th>Municipio</th>
      <th>Localidad</th>
      <th>Colonia</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registers.each do |register| %>
      <tr>
        <td><%= register.numero %></td>
        <td><%= register.nombregrupo %></td>
        <td><%= register.estado %></td>
        <td><%= register.municipio %></td>
        <td><%= register.localidad %></td>
        <td><%= register.colonia %></td>
        <td><%= register.status %></td>
        <td><%= link_to 'Show', register %></td>
        <td><%= link_to 'Edit', edit_register_path(register) %></td>
        <td><%= link_to 'Destroy', register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Register', new_register_path %>

app/views/registers/new.html.erb
<h1>New Register</h1>

<%= render 'form' %>

<%= link_to 'Back', registers_path %>

app/views/registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @register.numero %>
</p>

<p>
  <strong>Nombregrupo:</strong>
  <%= @register.nombregrupo %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @register.estado %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= @register.municipio %>
</p>

<p>
  <strong>Localidad:</strong>
  <%= @register.localidad %>
</p>

<p>
  <strong>Colonia:</strong>
  <%= @register.colonia %>
</p>

<p>
  <strong>Status:</strong>
  <%= @register.status %>
</p>

<%= link_to 'Edit', edit_register_path(@register) %> |
<%= link_to 'Back', registers_path %>

app/views/registros/edit.html.erb
<h1>Editing Registro</h1>

<%= render 'form' %>

<%= link_to 'Show', @registro %> |
<%= link_to 'Back', registros_path %>

app/views/registros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Registros</h1>

<%= search_form_for @search do |f| %>
  <div class="field">
    <%= f.label :nombre, "Name contains" %>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Nombregrupo</th>
      <th>Estado</th>
      <th>Municipio</th>
      <th>Localidad</th>
      <th>Colonia</th>
      <th>Disponible</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registros.each do |registro| %>
      <tr>
        <td><%= registro.numero %></td>
        <td><%= registro.nombregrupo %></td>
        <td><%= registro.estado %></td>
        <td><%= registro.municipio %></td>
        <td><%= registro.localidad %></td>
        <td><%= registro.colonia %></td>
        <td><%= registro.disponible %></td>
        <td><%= link_to 'Show', registro %></td>
        <td><%= link_to 'Edit', edit_registro_path(registro) %></td>
        <td><%= link_to 'Destroy', registro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Registro', new_registro_path %>

app/views/registros/new.html.erb
<h1>New Registro</h1>

<%= render 'form' %>

<%= link_to 'Back', registros_path %>

app/views/registros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @registro.numero %>
</p>

<p>
  <strong>Nombregrupo:</strong>
  <%= @registro.nombregrupo %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @registro.estado %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= @registro.municipio %>
</p>

<p>
  <strong>Localidad:</strong>
  <%= @registro.localidad %>
</p>

<p>
  <strong>Colonia:</strong>
  <%= @registro.colonia %>
</p>

<p>
  <strong>Disponible:</strong>
  <%= @registro.disponible %>
</p>

<%= link_to 'Edit', edit_registro_path(@registro) %> |
<%= link_to 'Back', registros_path %>

app/views/voluntarios/edit.html.erb
<div class="container">
<div class="row">
<div class="col-lg-12">
<h2>Editar Solicitud</h2>

<%= render 'form' %>
<div class="col-xs-4 col-xs-offset-2">
<%= link_to 'Show', @voluntario, class: 'btn btn-primary' %> 
<%= link_to 'Back', voluntarios_path, class: 'btn btn-primary' %>
</div>
</div>
</div>
</div>

app/views/voluntarios/index.html.erb
 
</h4>

<%= search_form_for(@search, :html => {class: "", role: "form"}) do |f| %>

  <div class="container">
   <h4><p id="notice"><%= notice %></p>
  <h2>Buscar Beneficiario</h2>
 <div class="row">
<div class="col-lg-3">

<div class="form-group">
  <%= f.label :contacto_cont, "Tipo de Contacto" %>       
  <%= f.select :contacto, [["Promotores voluntarios", "Promotores voluntarios"], ["Promotores capacitantes", "Promotores capacitantes"]], { :prompt => "Elegir" }, { class: "form-control" } %>
  </div>
</div>

<div class="col-lg-3">
  
<div class="form-group">
  <%= f.label :nombre_cont, "Nombre" %>
   <%= f.text_field :nombre_cont, class: "form-control", placeholder: "Nombre", autofocus: true %>
  </div>
</div>
<div class="col-lg-3">

  <div class="form-group">
    <%= f.label :apellido_cont, "Apellido" %>
   <%= f.text_field :apellido_cont, class: "form-control", placeholder: "Apellido", autofocus: true %>  
  </div>

</div>
<div class="col-lg-3">
 
<div class="form-group">
  
    <%= f.label :estado_cont, "Estado" %>
    
    <%= f.text_field :estado_cont, class: "form-control", placeholder: "Estado", autofocus: true %>
   
  </div>

</div>

  </div>



 <div class="row">
<div class="col-lg-3">
<%= f.label :municipio_cont, "Municipio" %>
    
 <%= f.text_field :municipio_cont, class: "form-control", placeholder: "Municipio", autofocus: true %>

</div>

<div class="col-lg-3">

<div class="form-group">
 
    <%= f.label :correo_electronico_cont, "Email" %>
   
    <%= f.text_field :correo_electronico_cont, class: "form-control", placeholder: "Email", autofocus: true %>
    </div>

</div>
<div class="col-lg-3">

  <div class="form-group">
 
    <%= f.label :telefono_cont, "Teléfono" %>
    
    <%= f.number_field :telefono_cont, class: "form-control", placeholder: "Teléfono", autofocus: true %>
   
  </div>

</div>
<div class="col-lg-3">
 
 <div class="form-group">
  
      <%= f.label :status_cont, "Status" %>
    
    <%= f.select :status_cont, [["Activo", "Activo"], ["Inactivo", "Inactivo"]], {:prompt => "Elegir"}, { class: "form-control" } %>
    </div>

</div>
</div>


<div class="row">

<div class="col-lg-3">
    <%= f.label :fecha_solicitud_cont, "Fecha de Solicitud" %>
   </br>
    <%= f.date_select :fecha_solicitud, {:prompt => { :day => 'Día', :month => 'Mes', :year => 'Año' }}, {:class => 'form-control date-select',}  %>
</div>


<div class="col-lg-3">
<div class="form-group">
      <%= f.label :fecha_autorizacion_cont, "Fecha de autorización" %></br>
    
    <%= f.date_select :fecha_solicitud, {:prompt => { :day => 'Día', :month => 'Mes', :year => 'Año' }}, {:class => 'form-control date-select'}  %>
    
  </div>

</div>

  </div>
<div class="row">
  <div class="form-group">
  <div class=" col-lg-1">

  <%= f.submit class: 'btn btn-primary btn-lg' %></div>
  </div>
</div>
  

  
<% end %>

</div></div>
<div class="container-fluid">
   <div class="row">
      <div class="col-lg-4 text-left">
        <%= link_to 'Agregar', new_voluntario_path, :class => "btn btn-primary btn_agregar" %>
      </div>
      <div class="col-lg-8 text-right">
        <%= will_paginate @voluntarios, renderer: BootstrapPagination::Rails %> 
     

    </div>
   <div class="col-lg-12  custyle">
    <table class="table table-striped custab">

  <thead>
    <tr>
    <th><%= sort_link(@search, :contacto, "Tipo de contacto") %></th>
    <th><%= sort_link(@search, :nombre, "Nombre") %></th>
    <th><%= sort_link(@search, :apellido, "Apellido") %></th>
    <th><%= sort_link(@search, :fecha_solicitud, "Fecha de solicitud") %></th>
    <th><%= sort_link(@search, :fecha_autorizacion, "Fecha de autorización") %></th>
    <th><%= sort_link(@search, :numero_registro, "N. de registro") %></th>
    <th><%= sort_link(@search, :estado, "Estado") %></th>
    <th><%= sort_link(@search, :municipio, "Municipio") %></th>
    <th><%= sort_link(@search, :localidad, "Localidad") %></th>
    <th><%= sort_link(@search, :colonia, "Colonia") %></th>
    <th><%= sort_link(@search, :correo_electronico, "Email") %></th> 
    <th><%= sort_link(@search, :telefono, "Teléfono") %></th>
    <th><%= sort_link(@search, :sub_grupos, "Sub grupos") %></th>
    <th><%= sort_link(@search, :obra_publica, "Obra pública") %></th>
    <th><%= sort_link(@search, :status, "Status") %></th>
    <th><%= sort_link(@search, :attachment, "Archivo") %></th>

    
    <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voluntarios.each do |voluntario| %>
      <tr>
        <td><%= voluntario.contacto %></td>
        <td><%= voluntario.nombre %></td>
        <td><%= voluntario.apellido %></td>
        <td><%= voluntario.fecha_solicitud %></td>
        <td><%= voluntario.fecha_autorizacion %></td>
        <td><%= voluntario.numero_registro %></td>
        <td><%= voluntario.estado %></td>
        <td><%= voluntario.municipio %></td>
        <td><%= voluntario.localidad %></td>
        <td><%= voluntario.colonia %></td>
        <td><%= voluntario.correo_electronico %></td>
        <td><%= voluntario.telefono %></td>
        <td><%= voluntario.sub_grupos %></td>
        <td><%= voluntario.obra_publica %></td>
        <td><%= voluntario.status %></td>
        <td><%= link_to "", voluntario.attachment_url, class:" glyphicon glyphicon-cloud-download" %></td>
        
        <td><%= link_to '', voluntario, class:"glyphicon glyphicon-eye-open" %></td>
        <td><%= link_to  edit_voluntario_path(voluntario), class:"glyphicon glyphicon-pencil" do  %>
        
        
        <% end %>
        </td>
        <td><%= link_to '', voluntario, class:"glyphicon glyphicon-remove", method: :delete, data: { confirm: 'Confirmar' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>




</div>
 
</div>
</div>
</div>

app/views/voluntarios/new.html.erb
<div class="container">
<div class="row">
<div class="col-md-12">
<h2>Crear Solicitud</h2>

<%= render 'form' %>
<div class="col-xs-4 col-xs-offset-2">
<%= link_to 'Back', voluntarios_path, class: 'btn btn-primary'  %>
</div>
</div>
</div>
</div>

app/views/voluntarios/show.html.erb
<div class="container">
<div class="row">
<div class="col-lg-12">
<blockquote>
<p id="notice"><%= notice %></p>
<p>
  <strong>Contacto:</strong>
  <%= @voluntario.contacto %>
</p>
</blockquote>
<p><blockquote>
  <strong>Nombre:</strong>
  <%= @voluntario.nombre %>
</p>
</blockquote>
<blockquote>
<p>
  <strong>Apellido:</strong>
  <%= @voluntario.apellido %>
</p>
</blockquote>
<blockquote>
<p>
  <strong>Fecha solicitud:</strong>
  <%= @voluntario.fecha_solicitud %>
</p>
</blockquote>
<blockquote>
<p>
  <strong>Fecha autorizacion:</strong>
  <%= @voluntario.fecha_autorizacion %>
</p>
</blockquote>
<blockquote>
<p>
  <strong>Numero registro:</strong>
  <%= @voluntario.numero_registro %>
</p>
</blockquote>
<blockquote>

<p>
  <strong>Estado:</strong>
  <%= @voluntario.estado %>
</p>
</blockquote>
<blockquote>
<p>
  <strong>Municipio:</strong>
  <%= @voluntario.municipio %>
</p>
</blockquote>
<blockquote>
<p>
  <strong>Localidad:</strong>
  <%= @voluntario.localidad %>
</p>
</blockquote>
<blockquote>
<p>
  <strong>Colonia:</strong>
  <%= @voluntario.colonia %>
</p>
</blockquote>
<blockquote>
<p>
  <strong>Correo electronico:</strong>
  <%= @voluntario.correo_electronico %>
</p>
</blockquote>
<blockquote>
<p>
  <strong>Telefono:</strong>
  <%= @voluntario.telefono %>
</p>
</blockquote>
<blockquote>
<p>
  <strong>Sub grupos:</strong>
  <%= @voluntario.sub_grupos %>
</p>
</blockquote>
<blockquote>
<p>
  <strong>Obra publica:</strong>
  <%= @voluntario.obra_publica %>
</p>
</blockquote>
<blockquote>
<p>
  <strong>Status:</strong>
  <%= @voluntario.status %>
</p>
</blockquote>
<blockquote>
<p>
  <strong>Attachment:</strong>
  <%= @voluntario.attachment %>
</p>
</blockquote>
<blockquote>
<p>
  <strong>Comentarios:</strong>
  <%= @voluntario.comentarios %>
</p>
</blockquote>


<%= link_to 'Edit', edit_voluntario_path(@voluntario), class: 'btn btn-primary' %> 
<%= link_to 'Back', voluntarios_path, class: 'btn btn-primary'%>
</div>
</div>
</div>